package entities.payloadComponents

case class PullRequest(_links:LinksWrapper2,
                       additions:Long,
                       assignee:User,
                       assignees:Array[User],
                       author_association:String,
                       base:Base,
                       body:String,
                       changed_files:Long,
                       closed_at:String,
                       comments:Long,
                       comments_url:String,
                       commits:Long,
                       commits_url:String,
                       created_at:String,
                       deletions:Long,
                       diff_url:String,
                       head:Base,
                       html_url:String,
                       id:Long,
                       issue_url:String,
                       labels:LabelsWrapper,
                       locked:Boolean,
                       maintainer_can_modify:Boolean,
                       merge_commit_sha:String,
                       mergeable:Boolean,
                       mergeable_state:String,
                       merged:Boolean,
                       merged_at:String,
                       merged_by:User,
                       milestone: Milestone,
                       number:Long,
                       patch_url:String,
                       rebaseable:Boolean,
                       requested_reviewers:Array[User],
                       requested_teams:Array[Team],
                       review_comment_url:String,
                       review_comments:Long,
                       review_comments_url:String,
                       state:String,
                       statuses_url:String,
                       title:String,
                       updated_at:String,
                       url:String,
                       user: User
                      )
